// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/merge-ats-go/pkg/models/shared"
	"net/http"
)

type ActivitiesMetaPostRetrieveRequest struct {
	// Token identifying the end user.
	XAccountToken string `header:"style=simple,explode=false,name=X-Account-Token"`
}

func (o *ActivitiesMetaPostRetrieveRequest) GetXAccountToken() string {
	if o == nil {
		return ""
	}
	return o.XAccountToken
}

type ActivitiesMetaPostRetrieveResponse struct {
	ContentType  string
	MetaResponse *shared.MetaResponse
	StatusCode   int
	RawResponse  *http.Response
}

func (o *ActivitiesMetaPostRetrieveResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ActivitiesMetaPostRetrieveResponse) GetMetaResponse() *shared.MetaResponse {
	if o == nil {
		return nil
	}
	return o.MetaResponse
}

func (o *ActivitiesMetaPostRetrieveResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ActivitiesMetaPostRetrieveResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
