// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/merge-ats-go/pkg/models/shared"
	"net/http"
)

type ApplicationsChangeStageCreateRequest struct {
	UpdateApplicationStageRequest *shared.UpdateApplicationStageRequest `request:"mediaType=application/json"`
	// Token identifying the end user.
	XAccountToken string `header:"style=simple,explode=false,name=X-Account-Token"`
	ID            string `pathParam:"style=simple,explode=false,name=id"`
	// Whether to include debug fields (such as log file links) in the response.
	IsDebugMode *bool `queryParam:"style=form,explode=true,name=is_debug_mode"`
	// Whether or not third-party updates should be run asynchronously.
	RunAsync *bool `queryParam:"style=form,explode=true,name=run_async"`
}

func (o *ApplicationsChangeStageCreateRequest) GetUpdateApplicationStageRequest() *shared.UpdateApplicationStageRequest {
	if o == nil {
		return nil
	}
	return o.UpdateApplicationStageRequest
}

func (o *ApplicationsChangeStageCreateRequest) GetXAccountToken() string {
	if o == nil {
		return ""
	}
	return o.XAccountToken
}

func (o *ApplicationsChangeStageCreateRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ApplicationsChangeStageCreateRequest) GetIsDebugMode() *bool {
	if o == nil {
		return nil
	}
	return o.IsDebugMode
}

func (o *ApplicationsChangeStageCreateRequest) GetRunAsync() *bool {
	if o == nil {
		return nil
	}
	return o.RunAsync
}

type ApplicationsChangeStageCreateResponse struct {
	ApplicationResponse *shared.ApplicationResponse
	ContentType         string
	StatusCode          int
	RawResponse         *http.Response
}

func (o *ApplicationsChangeStageCreateResponse) GetApplicationResponse() *shared.ApplicationResponse {
	if o == nil {
		return nil
	}
	return o.ApplicationResponse
}

func (o *ApplicationsChangeStageCreateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ApplicationsChangeStageCreateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ApplicationsChangeStageCreateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
