// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/merge-ats-go/pkg/models/shared"
	"net/http"
)

type AsyncPassthroughCreateFormSecurity struct {
	TokenAuth string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

func (o *AsyncPassthroughCreateFormSecurity) GetTokenAuth() string {
	if o == nil {
		return ""
	}
	return o.TokenAuth
}

type AsyncPassthroughCreateFormRequest struct {
	DataPassthroughRequest3 shared.DataPassthroughRequest3 `request:"mediaType=application/x-www-form-urlencoded"`
	// Token identifying the end user.
	XAccountToken string `header:"style=simple,explode=false,name=X-Account-Token"`
}

func (o *AsyncPassthroughCreateFormRequest) GetDataPassthroughRequest3() shared.DataPassthroughRequest3 {
	if o == nil {
		return shared.DataPassthroughRequest3{}
	}
	return o.DataPassthroughRequest3
}

func (o *AsyncPassthroughCreateFormRequest) GetXAccountToken() string {
	if o == nil {
		return ""
	}
	return o.XAccountToken
}

type AsyncPassthroughCreateFormResponse struct {
	AsyncPassthroughReciept *shared.AsyncPassthroughReciept
	ContentType             string
	StatusCode              int
	RawResponse             *http.Response
}

func (o *AsyncPassthroughCreateFormResponse) GetAsyncPassthroughReciept() *shared.AsyncPassthroughReciept {
	if o == nil {
		return nil
	}
	return o.AsyncPassthroughReciept
}

func (o *AsyncPassthroughCreateFormResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AsyncPassthroughCreateFormResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AsyncPassthroughCreateFormResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
