// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/merge-ats-go/pkg/models/shared"
	"net/http"
)

type CandidatesIgnoreCreateFormSecurity struct {
	TokenAuth string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

func (o *CandidatesIgnoreCreateFormSecurity) GetTokenAuth() string {
	if o == nil {
		return ""
	}
	return o.TokenAuth
}

type CandidatesIgnoreCreateFormRequest struct {
	IgnoreCommonModelRequest2 shared.IgnoreCommonModelRequest2 `request:"mediaType=application/x-www-form-urlencoded"`
	// Token identifying the end user.
	XAccountToken string `header:"style=simple,explode=false,name=X-Account-Token"`
	ModelID       string `pathParam:"style=simple,explode=false,name=model_id"`
}

func (o *CandidatesIgnoreCreateFormRequest) GetIgnoreCommonModelRequest2() shared.IgnoreCommonModelRequest2 {
	if o == nil {
		return shared.IgnoreCommonModelRequest2{}
	}
	return o.IgnoreCommonModelRequest2
}

func (o *CandidatesIgnoreCreateFormRequest) GetXAccountToken() string {
	if o == nil {
		return ""
	}
	return o.XAccountToken
}

func (o *CandidatesIgnoreCreateFormRequest) GetModelID() string {
	if o == nil {
		return ""
	}
	return o.ModelID
}

type CandidatesIgnoreCreateFormResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}

func (o *CandidatesIgnoreCreateFormResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CandidatesIgnoreCreateFormResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CandidatesIgnoreCreateFormResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
