// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/merge-ats-go/pkg/models/shared"
	"net/http"
)

type CandidatesIgnoreCreateJSONSecurity struct {
	TokenAuth string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

func (o *CandidatesIgnoreCreateJSONSecurity) GetTokenAuth() string {
	if o == nil {
		return ""
	}
	return o.TokenAuth
}

type CandidatesIgnoreCreateJSONRequest struct {
	IgnoreCommonModelRequest shared.IgnoreCommonModelRequest `request:"mediaType=application/json"`
	// Token identifying the end user.
	XAccountToken string `header:"style=simple,explode=false,name=X-Account-Token"`
	ModelID       string `pathParam:"style=simple,explode=false,name=model_id"`
}

func (o *CandidatesIgnoreCreateJSONRequest) GetIgnoreCommonModelRequest() shared.IgnoreCommonModelRequest {
	if o == nil {
		return shared.IgnoreCommonModelRequest{}
	}
	return o.IgnoreCommonModelRequest
}

func (o *CandidatesIgnoreCreateJSONRequest) GetXAccountToken() string {
	if o == nil {
		return ""
	}
	return o.XAccountToken
}

func (o *CandidatesIgnoreCreateJSONRequest) GetModelID() string {
	if o == nil {
		return ""
	}
	return o.ModelID
}

type CandidatesIgnoreCreateJSONResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}

func (o *CandidatesIgnoreCreateJSONResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CandidatesIgnoreCreateJSONResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CandidatesIgnoreCreateJSONResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
