// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/merge-ats-go/pkg/models/shared"
	"net/http"
)

// CandidatesRetrieveQueryParamExpand - Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
type CandidatesRetrieveQueryParamExpand string

const (
	CandidatesRetrieveQueryParamExpandApplications            CandidatesRetrieveQueryParamExpand = "applications"
	CandidatesRetrieveQueryParamExpandApplicationsAttachments CandidatesRetrieveQueryParamExpand = "applications,attachments"
	CandidatesRetrieveQueryParamExpandAttachments             CandidatesRetrieveQueryParamExpand = "attachments"
)

func (e CandidatesRetrieveQueryParamExpand) ToPointer() *CandidatesRetrieveQueryParamExpand {
	return &e
}

func (e *CandidatesRetrieveQueryParamExpand) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "applications":
		fallthrough
	case "applications,attachments":
		fallthrough
	case "attachments":
		*e = CandidatesRetrieveQueryParamExpand(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CandidatesRetrieveQueryParamExpand: %v", v)
	}
}

type CandidatesRetrieveRequest struct {
	// Token identifying the end user.
	XAccountToken string `header:"style=simple,explode=false,name=X-Account-Token"`
	ID            string `pathParam:"style=simple,explode=false,name=id"`
	// Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
	Expand *CandidatesRetrieveQueryParamExpand `queryParam:"style=form,explode=true,name=expand"`
	// Whether to include the original data Merge fetched from the third-party to produce these models.
	IncludeRemoteData *bool `queryParam:"style=form,explode=true,name=include_remote_data"`
}

func (o *CandidatesRetrieveRequest) GetXAccountToken() string {
	if o == nil {
		return ""
	}
	return o.XAccountToken
}

func (o *CandidatesRetrieveRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CandidatesRetrieveRequest) GetExpand() *CandidatesRetrieveQueryParamExpand {
	if o == nil {
		return nil
	}
	return o.Expand
}

func (o *CandidatesRetrieveRequest) GetIncludeRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.IncludeRemoteData
}

type CandidatesRetrieveResponse struct {
	Candidate *shared.Candidate
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CandidatesRetrieveResponse) GetCandidate() *shared.Candidate {
	if o == nil {
		return nil
	}
	return o.Candidate
}

func (o *CandidatesRetrieveResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CandidatesRetrieveResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CandidatesRetrieveResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
