// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/merge-ats-go/pkg/models/shared"
	"net/http"
)

// InterviewsRetrieveQueryParamExpand - Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
type InterviewsRetrieveQueryParamExpand string

const (
	InterviewsRetrieveQueryParamExpandApplication                                       InterviewsRetrieveQueryParamExpand = "application"
	InterviewsRetrieveQueryParamExpandApplicationJobInterviewStage                      InterviewsRetrieveQueryParamExpand = "application,job_interview_stage"
	InterviewsRetrieveQueryParamExpandInterviewers                                      InterviewsRetrieveQueryParamExpand = "interviewers"
	InterviewsRetrieveQueryParamExpandInterviewersApplication                           InterviewsRetrieveQueryParamExpand = "interviewers,application"
	InterviewsRetrieveQueryParamExpandInterviewersApplicationJobInterviewStage          InterviewsRetrieveQueryParamExpand = "interviewers,application,job_interview_stage"
	InterviewsRetrieveQueryParamExpandInterviewersJobInterviewStage                     InterviewsRetrieveQueryParamExpand = "interviewers,job_interview_stage"
	InterviewsRetrieveQueryParamExpandInterviewersOrganizer                             InterviewsRetrieveQueryParamExpand = "interviewers,organizer"
	InterviewsRetrieveQueryParamExpandInterviewersOrganizerApplication                  InterviewsRetrieveQueryParamExpand = "interviewers,organizer,application"
	InterviewsRetrieveQueryParamExpandInterviewersOrganizerApplicationJobInterviewStage InterviewsRetrieveQueryParamExpand = "interviewers,organizer,application,job_interview_stage"
	InterviewsRetrieveQueryParamExpandInterviewersOrganizerJobInterviewStage            InterviewsRetrieveQueryParamExpand = "interviewers,organizer,job_interview_stage"
	InterviewsRetrieveQueryParamExpandJobInterviewStage                                 InterviewsRetrieveQueryParamExpand = "job_interview_stage"
	InterviewsRetrieveQueryParamExpandOrganizer                                         InterviewsRetrieveQueryParamExpand = "organizer"
	InterviewsRetrieveQueryParamExpandOrganizerApplication                              InterviewsRetrieveQueryParamExpand = "organizer,application"
	InterviewsRetrieveQueryParamExpandOrganizerApplicationJobInterviewStage             InterviewsRetrieveQueryParamExpand = "organizer,application,job_interview_stage"
	InterviewsRetrieveQueryParamExpandOrganizerJobInterviewStage                        InterviewsRetrieveQueryParamExpand = "organizer,job_interview_stage"
)

func (e InterviewsRetrieveQueryParamExpand) ToPointer() *InterviewsRetrieveQueryParamExpand {
	return &e
}

func (e *InterviewsRetrieveQueryParamExpand) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "application":
		fallthrough
	case "application,job_interview_stage":
		fallthrough
	case "interviewers":
		fallthrough
	case "interviewers,application":
		fallthrough
	case "interviewers,application,job_interview_stage":
		fallthrough
	case "interviewers,job_interview_stage":
		fallthrough
	case "interviewers,organizer":
		fallthrough
	case "interviewers,organizer,application":
		fallthrough
	case "interviewers,organizer,application,job_interview_stage":
		fallthrough
	case "interviewers,organizer,job_interview_stage":
		fallthrough
	case "job_interview_stage":
		fallthrough
	case "organizer":
		fallthrough
	case "organizer,application":
		fallthrough
	case "organizer,application,job_interview_stage":
		fallthrough
	case "organizer,job_interview_stage":
		*e = InterviewsRetrieveQueryParamExpand(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InterviewsRetrieveQueryParamExpand: %v", v)
	}
}

// InterviewsRetrieveQueryParamRemoteFields - Deprecated. Use show_enum_origins.
type InterviewsRetrieveQueryParamRemoteFields string

const (
	InterviewsRetrieveQueryParamRemoteFieldsStatus InterviewsRetrieveQueryParamRemoteFields = "status"
)

func (e InterviewsRetrieveQueryParamRemoteFields) ToPointer() *InterviewsRetrieveQueryParamRemoteFields {
	return &e
}

func (e *InterviewsRetrieveQueryParamRemoteFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "status":
		*e = InterviewsRetrieveQueryParamRemoteFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InterviewsRetrieveQueryParamRemoteFields: %v", v)
	}
}

// InterviewsRetrieveQueryParamShowEnumOrigins - Which fields should be returned in non-normalized form.
type InterviewsRetrieveQueryParamShowEnumOrigins string

const (
	InterviewsRetrieveQueryParamShowEnumOriginsStatus InterviewsRetrieveQueryParamShowEnumOrigins = "status"
)

func (e InterviewsRetrieveQueryParamShowEnumOrigins) ToPointer() *InterviewsRetrieveQueryParamShowEnumOrigins {
	return &e
}

func (e *InterviewsRetrieveQueryParamShowEnumOrigins) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "status":
		*e = InterviewsRetrieveQueryParamShowEnumOrigins(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InterviewsRetrieveQueryParamShowEnumOrigins: %v", v)
	}
}

type InterviewsRetrieveRequest struct {
	// Token identifying the end user.
	XAccountToken string `header:"style=simple,explode=false,name=X-Account-Token"`
	// Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
	Expand *InterviewsRetrieveQueryParamExpand `queryParam:"style=form,explode=true,name=expand"`
	ID     string                              `pathParam:"style=simple,explode=false,name=id"`
	// Whether to include the original data Merge fetched from the third-party to produce these models.
	IncludeRemoteData *bool `queryParam:"style=form,explode=true,name=include_remote_data"`
	// Deprecated. Use show_enum_origins.
	RemoteFields *InterviewsRetrieveQueryParamRemoteFields `queryParam:"style=form,explode=true,name=remote_fields"`
	// Which fields should be returned in non-normalized form.
	ShowEnumOrigins *InterviewsRetrieveQueryParamShowEnumOrigins `queryParam:"style=form,explode=true,name=show_enum_origins"`
}

func (o *InterviewsRetrieveRequest) GetXAccountToken() string {
	if o == nil {
		return ""
	}
	return o.XAccountToken
}

func (o *InterviewsRetrieveRequest) GetExpand() *InterviewsRetrieveQueryParamExpand {
	if o == nil {
		return nil
	}
	return o.Expand
}

func (o *InterviewsRetrieveRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *InterviewsRetrieveRequest) GetIncludeRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.IncludeRemoteData
}

func (o *InterviewsRetrieveRequest) GetRemoteFields() *InterviewsRetrieveQueryParamRemoteFields {
	if o == nil {
		return nil
	}
	return o.RemoteFields
}

func (o *InterviewsRetrieveRequest) GetShowEnumOrigins() *InterviewsRetrieveQueryParamShowEnumOrigins {
	if o == nil {
		return nil
	}
	return o.ShowEnumOrigins
}

type InterviewsRetrieveResponse struct {
	// HTTP response content type for this operation
	ContentType        string
	ScheduledInterview *shared.ScheduledInterview
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *InterviewsRetrieveResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *InterviewsRetrieveResponse) GetScheduledInterview() *shared.ScheduledInterview {
	if o == nil {
		return nil
	}
	return o.ScheduledInterview
}

func (o *InterviewsRetrieveResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *InterviewsRetrieveResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
