// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/merge-ats-go/pkg/models/shared"
	"net/http"
)

type IssuesRetrieveRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *IssuesRetrieveRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type IssuesRetrieveResponse struct {
	ContentType string
	Issue       *shared.Issue
	StatusCode  int
	RawResponse *http.Response
}

func (o *IssuesRetrieveResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *IssuesRetrieveResponse) GetIssue() *shared.Issue {
	if o == nil {
		return nil
	}
	return o.Issue
}

func (o *IssuesRetrieveResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *IssuesRetrieveResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
