// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/merge-ats-go/pkg/models/shared"
	"net/http"
)

// JobsRetrieveQueryParamExpand - Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
type JobsRetrieveQueryParamExpand string

const (
	JobsRetrieveQueryParamExpandDepartments                                JobsRetrieveQueryParamExpand = "departments"
	JobsRetrieveQueryParamExpandDepartmentsHiringManagers                  JobsRetrieveQueryParamExpand = "departments,hiring_managers"
	JobsRetrieveQueryParamExpandDepartmentsHiringManagersRecruiters        JobsRetrieveQueryParamExpand = "departments,hiring_managers,recruiters"
	JobsRetrieveQueryParamExpandDepartmentsOffices                         JobsRetrieveQueryParamExpand = "departments,offices"
	JobsRetrieveQueryParamExpandDepartmentsOfficesHiringManagers           JobsRetrieveQueryParamExpand = "departments,offices,hiring_managers"
	JobsRetrieveQueryParamExpandDepartmentsOfficesHiringManagersRecruiters JobsRetrieveQueryParamExpand = "departments,offices,hiring_managers,recruiters"
	JobsRetrieveQueryParamExpandDepartmentsOfficesRecruiters               JobsRetrieveQueryParamExpand = "departments,offices,recruiters"
	JobsRetrieveQueryParamExpandDepartmentsRecruiters                      JobsRetrieveQueryParamExpand = "departments,recruiters"
	JobsRetrieveQueryParamExpandHiringManagers                             JobsRetrieveQueryParamExpand = "hiring_managers"
	JobsRetrieveQueryParamExpandHiringManagersRecruiters                   JobsRetrieveQueryParamExpand = "hiring_managers,recruiters"
	JobsRetrieveQueryParamExpandOffices                                    JobsRetrieveQueryParamExpand = "offices"
	JobsRetrieveQueryParamExpandOfficesHiringManagers                      JobsRetrieveQueryParamExpand = "offices,hiring_managers"
	JobsRetrieveQueryParamExpandOfficesHiringManagersRecruiters            JobsRetrieveQueryParamExpand = "offices,hiring_managers,recruiters"
	JobsRetrieveQueryParamExpandOfficesRecruiters                          JobsRetrieveQueryParamExpand = "offices,recruiters"
	JobsRetrieveQueryParamExpandRecruiters                                 JobsRetrieveQueryParamExpand = "recruiters"
)

func (e JobsRetrieveQueryParamExpand) ToPointer() *JobsRetrieveQueryParamExpand {
	return &e
}

func (e *JobsRetrieveQueryParamExpand) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "departments":
		fallthrough
	case "departments,hiring_managers":
		fallthrough
	case "departments,hiring_managers,recruiters":
		fallthrough
	case "departments,offices":
		fallthrough
	case "departments,offices,hiring_managers":
		fallthrough
	case "departments,offices,hiring_managers,recruiters":
		fallthrough
	case "departments,offices,recruiters":
		fallthrough
	case "departments,recruiters":
		fallthrough
	case "hiring_managers":
		fallthrough
	case "hiring_managers,recruiters":
		fallthrough
	case "offices":
		fallthrough
	case "offices,hiring_managers":
		fallthrough
	case "offices,hiring_managers,recruiters":
		fallthrough
	case "offices,recruiters":
		fallthrough
	case "recruiters":
		*e = JobsRetrieveQueryParamExpand(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JobsRetrieveQueryParamExpand: %v", v)
	}
}

// JobsRetrieveQueryParamRemoteFields - Deprecated. Use show_enum_origins.
type JobsRetrieveQueryParamRemoteFields string

const (
	JobsRetrieveQueryParamRemoteFieldsStatus JobsRetrieveQueryParamRemoteFields = "status"
)

func (e JobsRetrieveQueryParamRemoteFields) ToPointer() *JobsRetrieveQueryParamRemoteFields {
	return &e
}

func (e *JobsRetrieveQueryParamRemoteFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "status":
		*e = JobsRetrieveQueryParamRemoteFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JobsRetrieveQueryParamRemoteFields: %v", v)
	}
}

// JobsRetrieveQueryParamShowEnumOrigins - Which fields should be returned in non-normalized form.
type JobsRetrieveQueryParamShowEnumOrigins string

const (
	JobsRetrieveQueryParamShowEnumOriginsStatus JobsRetrieveQueryParamShowEnumOrigins = "status"
)

func (e JobsRetrieveQueryParamShowEnumOrigins) ToPointer() *JobsRetrieveQueryParamShowEnumOrigins {
	return &e
}

func (e *JobsRetrieveQueryParamShowEnumOrigins) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "status":
		*e = JobsRetrieveQueryParamShowEnumOrigins(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JobsRetrieveQueryParamShowEnumOrigins: %v", v)
	}
}

type JobsRetrieveRequest struct {
	// Token identifying the end user.
	XAccountToken string `header:"style=simple,explode=false,name=X-Account-Token"`
	// Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
	Expand *JobsRetrieveQueryParamExpand `queryParam:"style=form,explode=true,name=expand"`
	ID     string                        `pathParam:"style=simple,explode=false,name=id"`
	// Whether to include the original data Merge fetched from the third-party to produce these models.
	IncludeRemoteData *bool `queryParam:"style=form,explode=true,name=include_remote_data"`
	// Deprecated. Use show_enum_origins.
	RemoteFields *JobsRetrieveQueryParamRemoteFields `queryParam:"style=form,explode=true,name=remote_fields"`
	// Which fields should be returned in non-normalized form.
	ShowEnumOrigins *JobsRetrieveQueryParamShowEnumOrigins `queryParam:"style=form,explode=true,name=show_enum_origins"`
}

func (o *JobsRetrieveRequest) GetXAccountToken() string {
	if o == nil {
		return ""
	}
	return o.XAccountToken
}

func (o *JobsRetrieveRequest) GetExpand() *JobsRetrieveQueryParamExpand {
	if o == nil {
		return nil
	}
	return o.Expand
}

func (o *JobsRetrieveRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *JobsRetrieveRequest) GetIncludeRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.IncludeRemoteData
}

func (o *JobsRetrieveRequest) GetRemoteFields() *JobsRetrieveQueryParamRemoteFields {
	if o == nil {
		return nil
	}
	return o.RemoteFields
}

func (o *JobsRetrieveRequest) GetShowEnumOrigins() *JobsRetrieveQueryParamShowEnumOrigins {
	if o == nil {
		return nil
	}
	return o.ShowEnumOrigins
}

type JobsRetrieveResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Job         *shared.Job
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *JobsRetrieveResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *JobsRetrieveResponse) GetJob() *shared.Job {
	if o == nil {
		return nil
	}
	return o.Job
}

func (o *JobsRetrieveResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *JobsRetrieveResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
