// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/merge-ats-go/pkg/models/shared"
	"net/http"
)

type PassthroughCreateJSONSecurity struct {
	TokenAuth string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

func (o *PassthroughCreateJSONSecurity) GetTokenAuth() string {
	if o == nil {
		return ""
	}
	return o.TokenAuth
}

type PassthroughCreateJSONRequest struct {
	DataPassthroughRequest shared.DataPassthroughRequest `request:"mediaType=application/json"`
	// Token identifying the end user.
	XAccountToken string `header:"style=simple,explode=false,name=X-Account-Token"`
}

func (o *PassthroughCreateJSONRequest) GetDataPassthroughRequest() shared.DataPassthroughRequest {
	if o == nil {
		return shared.DataPassthroughRequest{}
	}
	return o.DataPassthroughRequest
}

func (o *PassthroughCreateJSONRequest) GetXAccountToken() string {
	if o == nil {
		return ""
	}
	return o.XAccountToken
}

type PassthroughCreateJSONResponse struct {
	ContentType    string
	RemoteResponse *shared.RemoteResponse
	StatusCode     int
	RawResponse    *http.Response
}

func (o *PassthroughCreateJSONResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PassthroughCreateJSONResponse) GetRemoteResponse() *shared.RemoteResponse {
	if o == nil {
		return nil
	}
	return o.RemoteResponse
}

func (o *PassthroughCreateJSONResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PassthroughCreateJSONResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
