// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/merge-ats-go/pkg/models/shared"
	"net/http"
)

// ScorecardsRetrieveQueryParamExpand - Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
type ScorecardsRetrieveQueryParamExpand string

const (
	ScorecardsRetrieveQueryParamExpandApplication                     ScorecardsRetrieveQueryParamExpand = "application"
	ScorecardsRetrieveQueryParamExpandApplicationInterview            ScorecardsRetrieveQueryParamExpand = "application,interview"
	ScorecardsRetrieveQueryParamExpandApplicationInterviewInterviewer ScorecardsRetrieveQueryParamExpand = "application,interview,interviewer"
	ScorecardsRetrieveQueryParamExpandApplicationInterviewer          ScorecardsRetrieveQueryParamExpand = "application,interviewer"
	ScorecardsRetrieveQueryParamExpandInterview                       ScorecardsRetrieveQueryParamExpand = "interview"
	ScorecardsRetrieveQueryParamExpandInterviewInterviewer            ScorecardsRetrieveQueryParamExpand = "interview,interviewer"
	ScorecardsRetrieveQueryParamExpandInterviewer                     ScorecardsRetrieveQueryParamExpand = "interviewer"
)

func (e ScorecardsRetrieveQueryParamExpand) ToPointer() *ScorecardsRetrieveQueryParamExpand {
	return &e
}

func (e *ScorecardsRetrieveQueryParamExpand) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "application":
		fallthrough
	case "application,interview":
		fallthrough
	case "application,interview,interviewer":
		fallthrough
	case "application,interviewer":
		fallthrough
	case "interview":
		fallthrough
	case "interview,interviewer":
		fallthrough
	case "interviewer":
		*e = ScorecardsRetrieveQueryParamExpand(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ScorecardsRetrieveQueryParamExpand: %v", v)
	}
}

// ScorecardsRetrieveQueryParamRemoteFields - Deprecated. Use show_enum_origins.
type ScorecardsRetrieveQueryParamRemoteFields string

const (
	ScorecardsRetrieveQueryParamRemoteFieldsOverallRecommendation ScorecardsRetrieveQueryParamRemoteFields = "overall_recommendation"
)

func (e ScorecardsRetrieveQueryParamRemoteFields) ToPointer() *ScorecardsRetrieveQueryParamRemoteFields {
	return &e
}

func (e *ScorecardsRetrieveQueryParamRemoteFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "overall_recommendation":
		*e = ScorecardsRetrieveQueryParamRemoteFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ScorecardsRetrieveQueryParamRemoteFields: %v", v)
	}
}

// ScorecardsRetrieveQueryParamShowEnumOrigins - Which fields should be returned in non-normalized form.
type ScorecardsRetrieveQueryParamShowEnumOrigins string

const (
	ScorecardsRetrieveQueryParamShowEnumOriginsOverallRecommendation ScorecardsRetrieveQueryParamShowEnumOrigins = "overall_recommendation"
)

func (e ScorecardsRetrieveQueryParamShowEnumOrigins) ToPointer() *ScorecardsRetrieveQueryParamShowEnumOrigins {
	return &e
}

func (e *ScorecardsRetrieveQueryParamShowEnumOrigins) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "overall_recommendation":
		*e = ScorecardsRetrieveQueryParamShowEnumOrigins(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ScorecardsRetrieveQueryParamShowEnumOrigins: %v", v)
	}
}

type ScorecardsRetrieveRequest struct {
	// Token identifying the end user.
	XAccountToken string `header:"style=simple,explode=false,name=X-Account-Token"`
	// Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
	Expand *ScorecardsRetrieveQueryParamExpand `queryParam:"style=form,explode=true,name=expand"`
	ID     string                              `pathParam:"style=simple,explode=false,name=id"`
	// Whether to include the original data Merge fetched from the third-party to produce these models.
	IncludeRemoteData *bool `queryParam:"style=form,explode=true,name=include_remote_data"`
	// Deprecated. Use show_enum_origins.
	RemoteFields *ScorecardsRetrieveQueryParamRemoteFields `queryParam:"style=form,explode=true,name=remote_fields"`
	// Which fields should be returned in non-normalized form.
	ShowEnumOrigins *ScorecardsRetrieveQueryParamShowEnumOrigins `queryParam:"style=form,explode=true,name=show_enum_origins"`
}

func (o *ScorecardsRetrieveRequest) GetXAccountToken() string {
	if o == nil {
		return ""
	}
	return o.XAccountToken
}

func (o *ScorecardsRetrieveRequest) GetExpand() *ScorecardsRetrieveQueryParamExpand {
	if o == nil {
		return nil
	}
	return o.Expand
}

func (o *ScorecardsRetrieveRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ScorecardsRetrieveRequest) GetIncludeRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.IncludeRemoteData
}

func (o *ScorecardsRetrieveRequest) GetRemoteFields() *ScorecardsRetrieveQueryParamRemoteFields {
	if o == nil {
		return nil
	}
	return o.RemoteFields
}

func (o *ScorecardsRetrieveRequest) GetShowEnumOrigins() *ScorecardsRetrieveQueryParamShowEnumOrigins {
	if o == nil {
		return nil
	}
	return o.ShowEnumOrigins
}

type ScorecardsRetrieveResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Scorecard   *shared.Scorecard
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ScorecardsRetrieveResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ScorecardsRetrieveResponse) GetScorecard() *shared.Scorecard {
	if o == nil {
		return nil
	}
	return o.Scorecard
}

func (o *ScorecardsRetrieveResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ScorecardsRetrieveResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
