// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/merge-ats-go/pkg/models/shared"
	"net/http"
)

type SelectiveSyncConfigurationsListSecurity struct {
	TokenAuth string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

func (o *SelectiveSyncConfigurationsListSecurity) GetTokenAuth() string {
	if o == nil {
		return ""
	}
	return o.TokenAuth
}

type SelectiveSyncConfigurationsListRequest struct {
	// Token identifying the end user.
	XAccountToken string `header:"style=simple,explode=false,name=X-Account-Token"`
}

func (o *SelectiveSyncConfigurationsListRequest) GetXAccountToken() string {
	if o == nil {
		return ""
	}
	return o.XAccountToken
}

type SelectiveSyncConfigurationsListResponse struct {
	ContentType                              string
	LinkedAccountSelectiveSyncConfigurations []shared.LinkedAccountSelectiveSyncConfiguration
	StatusCode                               int
	RawResponse                              *http.Response
}

func (o *SelectiveSyncConfigurationsListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SelectiveSyncConfigurationsListResponse) GetLinkedAccountSelectiveSyncConfigurations() []shared.LinkedAccountSelectiveSyncConfiguration {
	if o == nil {
		return nil
	}
	return o.LinkedAccountSelectiveSyncConfigurations
}

func (o *SelectiveSyncConfigurationsListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SelectiveSyncConfigurationsListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
