// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/merge-ats-go/pkg/models/shared"
	"net/http"
)

type SelectiveSyncConfigurationsListRequest struct {
	// Token identifying the end user.
	XAccountToken string `header:"style=simple,explode=false,name=X-Account-Token"`
}

func (o *SelectiveSyncConfigurationsListRequest) GetXAccountToken() string {
	if o == nil {
		return ""
	}
	return o.XAccountToken
}

type SelectiveSyncConfigurationsListResponse struct {
	// HTTP response content type for this operation
	ContentType                              string
	LinkedAccountSelectiveSyncConfigurations []shared.LinkedAccountSelectiveSyncConfiguration
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *SelectiveSyncConfigurationsListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SelectiveSyncConfigurationsListResponse) GetLinkedAccountSelectiveSyncConfigurations() []shared.LinkedAccountSelectiveSyncConfiguration {
	if o == nil {
		return nil
	}
	return o.LinkedAccountSelectiveSyncConfigurations
}

func (o *SelectiveSyncConfigurationsListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SelectiveSyncConfigurationsListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
