// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AccountIntegration struct {
	// Mapping of API endpoints to documentation urls for support. Example: {'GET': [['/common-model-scopes', 'https://docs.merge.dev/accounting/common-model-scopes/#common_model_scopes_retrieve'],['/common-model-actions', 'https://docs.merge.dev/accounting/common-model-actions/#common_model_actions_retrieve']], 'POST': []}
	APIEndpointsToDocumentationUrls map[string]interface{} `json:"api_endpoints_to_documentation_urls,omitempty"`
	// Category or categories this integration belongs to. Multiple categories should be comma separated, i.e. [ats, hris].
	Categories []CategoriesEnum `json:"categories,omitempty"`
	// The color of this integration used for buttons and text throughout the app and landing pages. <b>Choose a darker, saturated color.</b>
	Color *string `json:"color,omitempty"`
	// Company logo in rectangular shape. <b>Upload an image with a clear background.</b>
	Image *string `json:"image,omitempty"`
	// If checked, this integration will not appear in the linking flow, and will appear elsewhere with a Beta tag.
	IsInBeta *bool `json:"is_in_beta,omitempty"`
	// Company name.
	Name string  `json:"name"`
	Slug *string `json:"slug,omitempty"`
	// Company logo in square shape. <b>Upload an image with a white background.</b>
	SquareImage *string `json:"square_image,omitempty"`
}

func (o *AccountIntegration) GetAPIEndpointsToDocumentationUrls() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.APIEndpointsToDocumentationUrls
}

func (o *AccountIntegration) GetCategories() []CategoriesEnum {
	if o == nil {
		return nil
	}
	return o.Categories
}

func (o *AccountIntegration) GetColor() *string {
	if o == nil {
		return nil
	}
	return o.Color
}

func (o *AccountIntegration) GetImage() *string {
	if o == nil {
		return nil
	}
	return o.Image
}

func (o *AccountIntegration) GetIsInBeta() *bool {
	if o == nil {
		return nil
	}
	return o.IsInBeta
}

func (o *AccountIntegration) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *AccountIntegration) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *AccountIntegration) GetSquareImage() *string {
	if o == nil {
		return nil
	}
	return o.SquareImage
}
