// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AccountDetailsAndActionsIntegration struct {
	AvailableModelOperations []ModelOperation `json:"available_model_operations,omitempty"`
	Categories               []CategoriesEnum `json:"categories"`
	Color                    string           `json:"color"`
	Image                    *string          `json:"image,omitempty"`
	Name                     string           `json:"name"`
	PassthroughAvailable     bool             `json:"passthrough_available"`
	Slug                     string           `json:"slug"`
	SquareImage              *string          `json:"square_image,omitempty"`
}

func (o *AccountDetailsAndActionsIntegration) GetAvailableModelOperations() []ModelOperation {
	if o == nil {
		return nil
	}
	return o.AvailableModelOperations
}

func (o *AccountDetailsAndActionsIntegration) GetCategories() []CategoriesEnum {
	if o == nil {
		return []CategoriesEnum{}
	}
	return o.Categories
}

func (o *AccountDetailsAndActionsIntegration) GetColor() string {
	if o == nil {
		return ""
	}
	return o.Color
}

func (o *AccountDetailsAndActionsIntegration) GetImage() *string {
	if o == nil {
		return nil
	}
	return o.Image
}

func (o *AccountDetailsAndActionsIntegration) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *AccountDetailsAndActionsIntegration) GetPassthroughAvailable() bool {
	if o == nil {
		return false
	}
	return o.PassthroughAvailable
}

func (o *AccountDetailsAndActionsIntegration) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *AccountDetailsAndActionsIntegration) GetSquareImage() *string {
	if o == nil {
		return nil
	}
	return o.SquareImage
}
