// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ApplicationEndpointRequest struct {
	// # The Application Object
	// ### Description
	// The Application Object is used to represent a candidate's journey through a particular Job's recruiting process. If a Candidate applies for multiple Jobs, there will be a separate Application for each Job if the third-party integration allows it.
	//
	// ### Usage Example
	// Fetch from the `LIST Applications` endpoint and filter by `ID` to show all applications.
	Model        ApplicationRequest `json:"model" form:"name=model,json" multipartForm:"name=model,json"`
	RemoteUserID string             `json:"remote_user_id" form:"name=remote_user_id" multipartForm:"name=remote_user_id"`
}

func (o *ApplicationEndpointRequest) GetModel() ApplicationRequest {
	if o == nil {
		return ApplicationRequest{}
	}
	return o.Model
}

func (o *ApplicationEndpointRequest) GetRemoteUserID() string {
	if o == nil {
		return ""
	}
	return o.RemoteUserID
}
