// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Application - # The Application Object
// ### Description
// The Application Object is used to represent a candidate's journey through a particular Job's recruiting process. If a Candidate applies for multiple Jobs, there will be a separate Application for each Job if the third-party integration allows it.
//
// ### Usage Example
// Fetch from the `LIST Applications` endpoint and filter by `ID` to show all applications.
type Application struct {
	// When the application was submitted.
	AppliedAt *time.Time `json:"applied_at,omitempty"`
	// The candidate applying.
	Candidate *string `json:"candidate,omitempty"`
	// The user credited for this application.
	CreditedTo *string `json:"credited_to,omitempty"`
	// The application's current stage.
	CurrentStage  *string                `json:"current_stage,omitempty"`
	FieldMappings map[string]interface{} `json:"field_mappings,omitempty"`
	ID            *string                `json:"id,omitempty"`
	// The job being applied for.
	Job *string `json:"job,omitempty"`
	// This is the datetime that this object was last updated by Merge
	ModifiedAt *time.Time `json:"modified_at,omitempty"`
	// The application's reason for rejection.
	RejectReason *string `json:"reject_reason,omitempty"`
	// When the application was rejected.
	RejectedAt *time.Time   `json:"rejected_at,omitempty"`
	RemoteData []RemoteData `json:"remote_data,omitempty"`
	// The third-party API ID of the matching object.
	RemoteID         *string `json:"remote_id,omitempty"`
	RemoteWasDeleted *bool   `json:"remote_was_deleted,omitempty"`
	// The application's source.
	Source *string `json:"source,omitempty"`
}

func (o *Application) GetAppliedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.AppliedAt
}

func (o *Application) GetCandidate() *string {
	if o == nil {
		return nil
	}
	return o.Candidate
}

func (o *Application) GetCreditedTo() *string {
	if o == nil {
		return nil
	}
	return o.CreditedTo
}

func (o *Application) GetCurrentStage() *string {
	if o == nil {
		return nil
	}
	return o.CurrentStage
}

func (o *Application) GetFieldMappings() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.FieldMappings
}

func (o *Application) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Application) GetJob() *string {
	if o == nil {
		return nil
	}
	return o.Job
}

func (o *Application) GetModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ModifiedAt
}

func (o *Application) GetRejectReason() *string {
	if o == nil {
		return nil
	}
	return o.RejectReason
}

func (o *Application) GetRejectedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.RejectedAt
}

func (o *Application) GetRemoteData() []RemoteData {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *Application) GetRemoteID() *string {
	if o == nil {
		return nil
	}
	return o.RemoteID
}

func (o *Application) GetRemoteWasDeleted() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteWasDeleted
}

func (o *Application) GetSource() *string {
	if o == nil {
		return nil
	}
	return o.Source
}
