// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AttachmentResponse struct {
	Errors []ErrorValidationProblem `json:"errors"`
	Logs   []DebugModeLog           `json:"logs,omitempty"`
	// # The Attachment Object
	// ### Description
	// The `Attachment` object is used to represent a file attached to a candidate.
	// ### Usage Example
	// Fetch from the `LIST Attachments` endpoint and view attachments accessible by a company.
	Model    Attachment                 `json:"model"`
	Warnings []WarningValidationProblem `json:"warnings"`
}

func (o *AttachmentResponse) GetErrors() []ErrorValidationProblem {
	if o == nil {
		return []ErrorValidationProblem{}
	}
	return o.Errors
}

func (o *AttachmentResponse) GetLogs() []DebugModeLog {
	if o == nil {
		return nil
	}
	return o.Logs
}

func (o *AttachmentResponse) GetModel() Attachment {
	if o == nil {
		return Attachment{}
	}
	return o.Model
}

func (o *AttachmentResponse) GetWarnings() []WarningValidationProblem {
	if o == nil {
		return []WarningValidationProblem{}
	}
	return o.Warnings
}
