// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CandidateResponse struct {
	Errors []ErrorValidationProblem `json:"errors"`
	Logs   []DebugModeLog           `json:"logs,omitempty"`
	// # The Candidate Object
	// ### Description
	// The `Candidate` object is used to represent profile information about a given Candidate. Because it is specific to a Candidate, this information stays constant across applications.
	// ### Usage Example
	// Fetch from the `LIST Candidates` endpoint and filter by `ID` to show all candidates.
	Model    Candidate                  `json:"model"`
	Warnings []WarningValidationProblem `json:"warnings"`
}

func (o *CandidateResponse) GetErrors() []ErrorValidationProblem {
	if o == nil {
		return []ErrorValidationProblem{}
	}
	return o.Errors
}

func (o *CandidateResponse) GetLogs() []DebugModeLog {
	if o == nil {
		return nil
	}
	return o.Logs
}

func (o *CandidateResponse) GetModel() Candidate {
	if o == nil {
		return Candidate{}
	}
	return o.Model
}

func (o *CandidateResponse) GetWarnings() []WarningValidationProblem {
	if o == nil {
		return []WarningValidationProblem{}
	}
	return o.Warnings
}
