// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DebugModeLog struct {
	DashboardView string               `json:"dashboard_view"`
	LogID         string               `json:"log_id"`
	LogSummary    DebugModelLogSummary `json:"log_summary"`
}

func (o *DebugModeLog) GetDashboardView() string {
	if o == nil {
		return ""
	}
	return o.DashboardView
}

func (o *DebugModeLog) GetLogID() string {
	if o == nil {
		return ""
	}
	return o.LogID
}

func (o *DebugModeLog) GetLogSummary() DebugModelLogSummary {
	if o == nil {
		return DebugModelLogSummary{}
	}
	return o.LogSummary
}
