// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

// EEOCDisabilityStatus - * `YES_I_HAVE_A_DISABILITY_OR_PREVIOUSLY_HAD_A_DISABILITY` - YES_I_HAVE_A_DISABILITY_OR_PREVIOUSLY_HAD_A_DISABILITY
// * `NO_I_DONT_HAVE_A_DISABILITY` - NO_I_DONT_HAVE_A_DISABILITY
// * `I_DONT_WISH_TO_ANSWER` - I_DONT_WISH_TO_ANSWER
type EEOCDisabilityStatus string

const (
	EEOCDisabilityStatusYesIHaveADisabilityOrPreviouslyHadADisability EEOCDisabilityStatus = "YES_I_HAVE_A_DISABILITY_OR_PREVIOUSLY_HAD_A_DISABILITY"
	EEOCDisabilityStatusNoIDontHaveADisability                        EEOCDisabilityStatus = "NO_I_DONT_HAVE_A_DISABILITY"
	EEOCDisabilityStatusIDontWishToAnswer                             EEOCDisabilityStatus = "I_DONT_WISH_TO_ANSWER"
)

func (e EEOCDisabilityStatus) ToPointer() *EEOCDisabilityStatus {
	return &e
}

func (e *EEOCDisabilityStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "YES_I_HAVE_A_DISABILITY_OR_PREVIOUSLY_HAD_A_DISABILITY":
		fallthrough
	case "NO_I_DONT_HAVE_A_DISABILITY":
		fallthrough
	case "I_DONT_WISH_TO_ANSWER":
		*e = EEOCDisabilityStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EEOCDisabilityStatus: %v", v)
	}
}

// EEOCGender - * `MALE` - MALE
// * `FEMALE` - FEMALE
// * `NON-BINARY` - NON-BINARY
// * `OTHER` - OTHER
// * `DECLINE_TO_SELF_IDENTIFY` - DECLINE_TO_SELF_IDENTIFY
type EEOCGender string

const (
	EEOCGenderMale                  EEOCGender = "MALE"
	EEOCGenderFemale                EEOCGender = "FEMALE"
	EEOCGenderNonBinary             EEOCGender = "NON-BINARY"
	EEOCGenderOther                 EEOCGender = "OTHER"
	EEOCGenderDeclineToSelfIdentify EEOCGender = "DECLINE_TO_SELF_IDENTIFY"
)

func (e EEOCGender) ToPointer() *EEOCGender {
	return &e
}

func (e *EEOCGender) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "MALE":
		fallthrough
	case "FEMALE":
		fallthrough
	case "NON-BINARY":
		fallthrough
	case "OTHER":
		fallthrough
	case "DECLINE_TO_SELF_IDENTIFY":
		*e = EEOCGender(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EEOCGender: %v", v)
	}
}

// EEOCRace - * `AMERICAN_INDIAN_OR_ALASKAN_NATIVE` - AMERICAN_INDIAN_OR_ALASKAN_NATIVE
// * `ASIAN` - ASIAN
// * `BLACK_OR_AFRICAN_AMERICAN` - BLACK_OR_AFRICAN_AMERICAN
// * `HISPANIC_OR_LATINO` - HISPANIC_OR_LATINO
// * `WHITE` - WHITE
// * `NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER` - NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER
// * `TWO_OR_MORE_RACES` - TWO_OR_MORE_RACES
// * `DECLINE_TO_SELF_IDENTIFY` - DECLINE_TO_SELF_IDENTIFY
type EEOCRace string

const (
	EEOCRaceAmericanIndianOrAlaskanNative        EEOCRace = "AMERICAN_INDIAN_OR_ALASKAN_NATIVE"
	EEOCRaceAsian                                EEOCRace = "ASIAN"
	EEOCRaceBlackOrAfricanAmerican               EEOCRace = "BLACK_OR_AFRICAN_AMERICAN"
	EEOCRaceHispanicOrLatino                     EEOCRace = "HISPANIC_OR_LATINO"
	EEOCRaceWhite                                EEOCRace = "WHITE"
	EEOCRaceNativeHawaiianOrOtherPacificIslander EEOCRace = "NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER"
	EEOCRaceTwoOrMoreRaces                       EEOCRace = "TWO_OR_MORE_RACES"
	EEOCRaceDeclineToSelfIdentify                EEOCRace = "DECLINE_TO_SELF_IDENTIFY"
)

func (e EEOCRace) ToPointer() *EEOCRace {
	return &e
}

func (e *EEOCRace) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AMERICAN_INDIAN_OR_ALASKAN_NATIVE":
		fallthrough
	case "ASIAN":
		fallthrough
	case "BLACK_OR_AFRICAN_AMERICAN":
		fallthrough
	case "HISPANIC_OR_LATINO":
		fallthrough
	case "WHITE":
		fallthrough
	case "NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER":
		fallthrough
	case "TWO_OR_MORE_RACES":
		fallthrough
	case "DECLINE_TO_SELF_IDENTIFY":
		*e = EEOCRace(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EEOCRace: %v", v)
	}
}

// EEOCVeteranStatus - * `I_AM_NOT_A_PROTECTED_VETERAN` - I_AM_NOT_A_PROTECTED_VETERAN
// * `I_IDENTIFY_AS_ONE_OR_MORE_OF_THE_CLASSIFICATIONS_OF_A_PROTECTED_VETERAN` - I_IDENTIFY_AS_ONE_OR_MORE_OF_THE_CLASSIFICATIONS_OF_A_PROTECTED_VETERAN
// * `I_DONT_WISH_TO_ANSWER` - I_DONT_WISH_TO_ANSWER
type EEOCVeteranStatus string

const (
	EEOCVeteranStatusIAmNotAProtectedVeteran                                     EEOCVeteranStatus = "I_AM_NOT_A_PROTECTED_VETERAN"
	EEOCVeteranStatusIIdentifyAsOneOrMoreOfTheClassificationsOfAProtectedVeteran EEOCVeteranStatus = "I_IDENTIFY_AS_ONE_OR_MORE_OF_THE_CLASSIFICATIONS_OF_A_PROTECTED_VETERAN"
	EEOCVeteranStatusIDontWishToAnswer                                           EEOCVeteranStatus = "I_DONT_WISH_TO_ANSWER"
)

func (e EEOCVeteranStatus) ToPointer() *EEOCVeteranStatus {
	return &e
}

func (e *EEOCVeteranStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "I_AM_NOT_A_PROTECTED_VETERAN":
		fallthrough
	case "I_IDENTIFY_AS_ONE_OR_MORE_OF_THE_CLASSIFICATIONS_OF_A_PROTECTED_VETERAN":
		fallthrough
	case "I_DONT_WISH_TO_ANSWER":
		*e = EEOCVeteranStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EEOCVeteranStatus: %v", v)
	}
}

// Eeoc - # The EEOC Object
// ### Description
// The `EEOC` object is used to represent the Equal Employment Opportunity Commission information for a candidate (race, gender, veteran status, disability status).
// ### Usage Example
// Fetch from the `LIST EEOCs` endpoint and filter by `candidate` to show all EEOC information for a candidate.
type Eeoc struct {
	// The candidate being represented.
	Candidate *string `json:"candidate,omitempty"`
	// The candidate's disability status.
	//
	// * `YES_I_HAVE_A_DISABILITY_OR_PREVIOUSLY_HAD_A_DISABILITY` - YES_I_HAVE_A_DISABILITY_OR_PREVIOUSLY_HAD_A_DISABILITY
	// * `NO_I_DONT_HAVE_A_DISABILITY` - NO_I_DONT_HAVE_A_DISABILITY
	// * `I_DONT_WISH_TO_ANSWER` - I_DONT_WISH_TO_ANSWER
	DisabilityStatus *EEOCDisabilityStatus  `json:"disability_status,omitempty"`
	FieldMappings    map[string]interface{} `json:"field_mappings,omitempty"`
	// The candidate's gender.
	//
	// * `MALE` - MALE
	// * `FEMALE` - FEMALE
	// * `NON-BINARY` - NON-BINARY
	// * `OTHER` - OTHER
	// * `DECLINE_TO_SELF_IDENTIFY` - DECLINE_TO_SELF_IDENTIFY
	Gender *EEOCGender `json:"gender,omitempty"`
	ID     *string     `json:"id,omitempty"`
	// This is the datetime that this object was last updated by Merge
	ModifiedAt *time.Time `json:"modified_at,omitempty"`
	// The candidate's race.
	//
	// * `AMERICAN_INDIAN_OR_ALASKAN_NATIVE` - AMERICAN_INDIAN_OR_ALASKAN_NATIVE
	// * `ASIAN` - ASIAN
	// * `BLACK_OR_AFRICAN_AMERICAN` - BLACK_OR_AFRICAN_AMERICAN
	// * `HISPANIC_OR_LATINO` - HISPANIC_OR_LATINO
	// * `WHITE` - WHITE
	// * `NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER` - NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER
	// * `TWO_OR_MORE_RACES` - TWO_OR_MORE_RACES
	// * `DECLINE_TO_SELF_IDENTIFY` - DECLINE_TO_SELF_IDENTIFY
	Race       *EEOCRace    `json:"race,omitempty"`
	RemoteData []RemoteData `json:"remote_data,omitempty"`
	// The third-party API ID of the matching object.
	RemoteID *string `json:"remote_id,omitempty"`
	// Indicates whether or not this object has been deleted by third party webhooks.
	RemoteWasDeleted *bool `json:"remote_was_deleted,omitempty"`
	// When the information was submitted.
	SubmittedAt *time.Time `json:"submitted_at,omitempty"`
	// The candidate's veteran status.
	//
	// * `I_AM_NOT_A_PROTECTED_VETERAN` - I_AM_NOT_A_PROTECTED_VETERAN
	// * `I_IDENTIFY_AS_ONE_OR_MORE_OF_THE_CLASSIFICATIONS_OF_A_PROTECTED_VETERAN` - I_IDENTIFY_AS_ONE_OR_MORE_OF_THE_CLASSIFICATIONS_OF_A_PROTECTED_VETERAN
	// * `I_DONT_WISH_TO_ANSWER` - I_DONT_WISH_TO_ANSWER
	VeteranStatus *EEOCVeteranStatus `json:"veteran_status,omitempty"`
}

func (o *Eeoc) GetCandidate() *string {
	if o == nil {
		return nil
	}
	return o.Candidate
}

func (o *Eeoc) GetDisabilityStatus() *EEOCDisabilityStatus {
	if o == nil {
		return nil
	}
	return o.DisabilityStatus
}

func (o *Eeoc) GetFieldMappings() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.FieldMappings
}

func (o *Eeoc) GetGender() *EEOCGender {
	if o == nil {
		return nil
	}
	return o.Gender
}

func (o *Eeoc) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Eeoc) GetModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ModifiedAt
}

func (o *Eeoc) GetRace() *EEOCRace {
	if o == nil {
		return nil
	}
	return o.Race
}

func (o *Eeoc) GetRemoteData() []RemoteData {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *Eeoc) GetRemoteID() *string {
	if o == nil {
		return nil
	}
	return o.RemoteID
}

func (o *Eeoc) GetRemoteWasDeleted() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteWasDeleted
}

func (o *Eeoc) GetSubmittedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.SubmittedAt
}

func (o *Eeoc) GetVeteranStatus() *EEOCVeteranStatus {
	if o == nil {
		return nil
	}
	return o.VeteranStatus
}
