// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GenerateRemoteKeyRequest - # The GenerateRemoteKey Object
// ### Description
// The `GenerateRemoteKey` object is used to represent a request for a new remote key.
//
// ### Usage Example
// Post a `GenerateRemoteKey` to create a new remote key.
type GenerateRemoteKeyRequest struct {
	Name string `json:"name"`
}

func (o *GenerateRemoteKeyRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
