// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// IgnoreCommonModelRequestReason - * `GENERAL_CUSTOMER_REQUEST` - GENERAL_CUSTOMER_REQUEST
// * `GDPR` - GDPR
// * `OTHER` - OTHER
type IgnoreCommonModelRequestReason string

const (
	IgnoreCommonModelRequestReasonGeneralCustomerRequest IgnoreCommonModelRequestReason = "GENERAL_CUSTOMER_REQUEST"
	IgnoreCommonModelRequestReasonGdpr                   IgnoreCommonModelRequestReason = "GDPR"
	IgnoreCommonModelRequestReasonOther                  IgnoreCommonModelRequestReason = "OTHER"
)

func (e IgnoreCommonModelRequestReason) ToPointer() *IgnoreCommonModelRequestReason {
	return &e
}

func (e *IgnoreCommonModelRequestReason) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "GENERAL_CUSTOMER_REQUEST":
		fallthrough
	case "GDPR":
		fallthrough
	case "OTHER":
		*e = IgnoreCommonModelRequestReason(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IgnoreCommonModelRequestReason: %v", v)
	}
}

type IgnoreCommonModelRequest struct {
	Message *string                        `json:"message,omitempty"`
	Reason  IgnoreCommonModelRequestReason `json:"reason"`
}

func (o *IgnoreCommonModelRequest) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *IgnoreCommonModelRequest) GetReason() IgnoreCommonModelRequestReason {
	if o == nil {
		return IgnoreCommonModelRequestReason("")
	}
	return o.Reason
}
