// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/merge-ats-go/pkg/utils"
	"time"
)

// JobInterviewStage - # The JobInterviewStage Object
// ### Description
// The `JobInterviewStage` object is used to represent a particular recruiting stage for an `Application`. A given `Application` typically has the `JobInterviewStage` object represented in the current_stage field.
// ### Usage Example
// Fetch from the `LIST JobInterviewStages` endpoint and view the job interview stages used by a company.
type JobInterviewStage struct {
	FieldMappings map[string]interface{} `json:"field_mappings,omitempty"`
	ID            *string                `json:"id,omitempty"`
	// This field is populated only if the stage is specific to a particular job. If the stage is generic, this field will not be populated.
	Job *string `json:"job,omitempty"`
	// This is the datetime that this object was last updated by Merge
	ModifiedAt *time.Time `json:"modified_at,omitempty"`
	// Standard stage names are offered by ATS systems but can be modified by users.
	Name       *string      `json:"name,omitempty"`
	RemoteData []RemoteData `json:"remote_data,omitempty"`
	// The third-party API ID of the matching object.
	RemoteID *string `json:"remote_id,omitempty"`
	// Indicates whether or not this object has been deleted by third party webhooks.
	RemoteWasDeleted *bool `json:"remote_was_deleted,omitempty"`
	// The stage’s order, with the lowest values ordered first. If the third-party does not return details on the order of stages, this field will not be populated.
	StageOrder *int64 `json:"stage_order,omitempty"`
}

func (j JobInterviewStage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(j, "", false)
}

func (j *JobInterviewStage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &j, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *JobInterviewStage) GetFieldMappings() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.FieldMappings
}

func (o *JobInterviewStage) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *JobInterviewStage) GetJob() *string {
	if o == nil {
		return nil
	}
	return o.Job
}

func (o *JobInterviewStage) GetModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ModifiedAt
}

func (o *JobInterviewStage) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *JobInterviewStage) GetRemoteData() []RemoteData {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *JobInterviewStage) GetRemoteID() *string {
	if o == nil {
		return nil
	}
	return o.RemoteID
}

func (o *JobInterviewStage) GetRemoteWasDeleted() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteWasDeleted
}

func (o *JobInterviewStage) GetStageOrder() *int64 {
	if o == nil {
		return nil
	}
	return o.StageOrder
}
