// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type LinkedAccountConditionRequest struct {
	// The ID indicating which condition schema to use for a specific condition.
	ConditionSchemaID string `json:"condition_schema_id"`
	// The operator for a specific condition.
	Operator string `json:"operator"`
	// The value for a specific condition.
	Value interface{} `json:"value"`
}

func (o *LinkedAccountConditionRequest) GetConditionSchemaID() string {
	if o == nil {
		return ""
	}
	return o.ConditionSchemaID
}

func (o *LinkedAccountConditionRequest) GetOperator() string {
	if o == nil {
		return ""
	}
	return o.Operator
}

func (o *LinkedAccountConditionRequest) GetValue() interface{} {
	if o == nil {
		return nil
	}
	return o.Value
}
