// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type LinkedAccountCondition struct {
	// The common model for a specific condition.
	CommonModel *string `json:"common_model,omitempty"`
	// The ID indicating which condition schema to use for a specific condition.
	ConditionSchemaID string `json:"condition_schema_id"`
	// The name of the field on the common model that this condition corresponds to, if they conceptually match. e.g. "location_type".
	FieldName string `json:"field_name"`
	// User-facing *native condition* name. e.g. "Skip Manager".
	NativeName string `json:"native_name"`
	// The operator for a specific condition.
	Operator string `json:"operator"`
	// The value for a condition.
	Value interface{} `json:"value,omitempty"`
}

func (o *LinkedAccountCondition) GetCommonModel() *string {
	if o == nil {
		return nil
	}
	return o.CommonModel
}

func (o *LinkedAccountCondition) GetConditionSchemaID() string {
	if o == nil {
		return ""
	}
	return o.ConditionSchemaID
}

func (o *LinkedAccountCondition) GetFieldName() string {
	if o == nil {
		return ""
	}
	return o.FieldName
}

func (o *LinkedAccountCondition) GetNativeName() string {
	if o == nil {
		return ""
	}
	return o.NativeName
}

func (o *LinkedAccountCondition) GetOperator() string {
	if o == nil {
		return ""
	}
	return o.Operator
}

func (o *LinkedAccountCondition) GetValue() interface{} {
	if o == nil {
		return nil
	}
	return o.Value
}
