// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OperatorSchema struct {
	// Whether the operator can be repeated multiple times.
	IsUnique *bool `json:"is_unique,omitempty"`
	// The operator for which an operator schema is defined.
	Operator *string `json:"operator,omitempty"`
}

func (o *OperatorSchema) GetIsUnique() *bool {
	if o == nil {
		return nil
	}
	return o.IsUnique
}

func (o *OperatorSchema) GetOperator() *string {
	if o == nil {
		return nil
	}
	return o.Operator
}
