// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PaginatedSyncStatusList struct {
	Next     *string      `json:"next,omitempty"`
	Previous *string      `json:"previous,omitempty"`
	Results  []SyncStatus `json:"results,omitempty"`
}

func (o *PaginatedSyncStatusList) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *PaginatedSyncStatusList) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *PaginatedSyncStatusList) GetResults() []SyncStatus {
	if o == nil {
		return nil
	}
	return o.Results
}
