// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PaginatedRejectReasonList struct {
	Next     *string        `json:"next,omitempty"`
	Previous *string        `json:"previous,omitempty"`
	Results  []RejectReason `json:"results,omitempty"`
}

func (o *PaginatedRejectReasonList) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *PaginatedRejectReasonList) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *PaginatedRejectReasonList) GetResults() []RejectReason {
	if o == nil {
		return nil
	}
	return o.Results
}
