// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RemoteKey - # The RemoteKey Object
// ### Description
// The `RemoteKey` object is used to represent a request for a new remote key.
//
// ### Usage Example
// Post a `GenerateRemoteKey` to receive a new `RemoteKey`.
type RemoteKey struct {
	Key  string `json:"key"`
	Name string `json:"name"`
}

func (o *RemoteKey) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *RemoteKey) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
