// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// URLRequestURLType - * `PERSONAL` - PERSONAL
// * `COMPANY` - COMPANY
// * `PORTFOLIO` - PORTFOLIO
// * `BLOG` - BLOG
// * `SOCIAL_MEDIA` - SOCIAL_MEDIA
// * `OTHER` - OTHER
// * `JOB_POSTING` - JOB_POSTING
type URLRequestURLType string

const (
	URLRequestURLTypePersonal    URLRequestURLType = "PERSONAL"
	URLRequestURLTypeCompany     URLRequestURLType = "COMPANY"
	URLRequestURLTypePortfolio   URLRequestURLType = "PORTFOLIO"
	URLRequestURLTypeBlog        URLRequestURLType = "BLOG"
	URLRequestURLTypeSocialMedia URLRequestURLType = "SOCIAL_MEDIA"
	URLRequestURLTypeOther       URLRequestURLType = "OTHER"
	URLRequestURLTypeJobPosting  URLRequestURLType = "JOB_POSTING"
)

func (e URLRequestURLType) ToPointer() *URLRequestURLType {
	return &e
}

func (e *URLRequestURLType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PERSONAL":
		fallthrough
	case "COMPANY":
		fallthrough
	case "PORTFOLIO":
		fallthrough
	case "BLOG":
		fallthrough
	case "SOCIAL_MEDIA":
		fallthrough
	case "OTHER":
		fallthrough
	case "JOB_POSTING":
		*e = URLRequestURLType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for URLRequestURLType: %v", v)
	}
}

// URLRequest - # The Url Object
// ### Description
// The `Url` object is used to represent hyperlinks associated with the parent model.
// ### Usage Example
// Fetch from the `GET Candidate` endpoint and view their website urls.
type URLRequest struct {
	IntegrationParams   map[string]interface{} `json:"integration_params,omitempty"`
	LinkedAccountParams map[string]interface{} `json:"linked_account_params,omitempty"`
	// The type of site.
	//
	// * `PERSONAL` - PERSONAL
	// * `COMPANY` - COMPANY
	// * `PORTFOLIO` - PORTFOLIO
	// * `BLOG` - BLOG
	// * `SOCIAL_MEDIA` - SOCIAL_MEDIA
	// * `OTHER` - OTHER
	// * `JOB_POSTING` - JOB_POSTING
	URLType *URLRequestURLType `json:"url_type,omitempty"`
	// The site's url.
	Value *string `json:"value,omitempty"`
}

func (o *URLRequest) GetIntegrationParams() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.IntegrationParams
}

func (o *URLRequest) GetLinkedAccountParams() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.LinkedAccountParams
}

func (o *URLRequest) GetURLType() *URLRequestURLType {
	if o == nil {
		return nil
	}
	return o.URLType
}

func (o *URLRequest) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}
