// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ValidationProblemSource struct {
	Pointer string `json:"pointer"`
}

func (o *ValidationProblemSource) GetPointer() string {
	if o == nil {
		return ""
	}
	return o.Pointer
}
